// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OutputWindowFilter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OutputWindowFilterString = "e2ce11aa-cead-40b7-bd63-f6c1c69de119";
        public static Guid OutputWindowFilter = new Guid(OutputWindowFilterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FilterGroup = 0x0001;
        public const int Filter = 0x0100;
        public const int EmptyList = 0x0200;
    }
}